package com.Multi.tenant_SaaS_Project_Management_System.Mappers;


import com.Multi.tenant_SaaS_Project_Management_System.DTOs.UserActivityRequest;
import com.Multi.tenant_SaaS_Project_Management_System.DTOs.UserActivityResponse;
import com.Multi.tenant_SaaS_Project_Management_System.Entities.UserActivity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface UserActivityMapper {

    UserActivityMapper INSTANCE = Mappers.getMapper(UserActivityMapper.class);

    @Mapping(target = "id", ignore = true)
        // Auto-generated by DB
    UserActivity toEntity(UserActivityRequest request);

    UserActivityResponse toResponse(UserActivity entity);
}

